import { test } from "node:test";
import assert from "node:assert";
import { metaStateSweepTool } from "../tools/meta-state-sweep-tool.js";
import { loopDescribeTool } from "../tools/loop-describe-tool.js";
import { resolveRoot } from "#lib/resolve-root.js";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = resolveRoot();

test("Phase 7: meta_state_sweep generates docs/registry-summary.md on apply", async () => {
  // Need operator mode to apply
  const original = process.env.OPERATOR_MODE;
  process.env.OPERATOR_MODE = "1";
  try {
    const result = await metaStateSweepTool.handler({ apply: true });
    const text = JSON.parse(result.content[0].text);
    assert.strictEqual(text.swept, true);
  } finally {
    process.env.OPERATOR_MODE = original;
  }

  const summaryPath = join(root, "docs", "registry-summary.md");
  assert.ok(existsSync(summaryPath), "docs/registry-summary.md should exist after sweep");

  const md = readFileSync(summaryPath, "utf8");
  assert.ok(md.includes("<!-- Auto-generated by meta_state_sweep"), "Should have auto-generated header");
  assert.ok(md.includes("## Counts"), "Should have Counts section");
  assert.ok(md.includes("## Coverage"), "Should have Coverage section");
  assert.ok(md.includes("## Top References"), "Should have Top References section");
  assert.ok(md.includes("## Drift"), "Should have Drift section");
});

test("Phase 7: warm tier includes registry_summary field", async () => {
  const result = await loopDescribeTool.handler({ tier: "warm" });
  const text = JSON.parse(result.content[0].text);
  assert.ok(text.registry_summary, "warm tier should have registry_summary");
  assert.ok(text.registry_summary.counts, "registry_summary should have counts");
  assert.ok(text.registry_summary.coverage, "registry_summary should have coverage");
  assert.ok(text.registry_summary.top_references, "registry_summary should have top_references");
  assert.ok(text.registry_summary.drift, "registry_summary should have drift");
  assert.ok(text.registry_summary.last_generated_at, "registry_summary should have last_generated_at");
});

test("Phase 7: registry_summary is idempotent on re-run", async () => {
  const original = process.env.OPERATOR_MODE;
  process.env.OPERATOR_MODE = "1";
  try {
    await metaStateSweepTool.handler({ apply: true });
  } finally {
    process.env.OPERATOR_MODE = original;
  }

  const summaryPath = join(root, "docs", "registry-summary.md");
  const first = readFileSync(summaryPath, "utf8");

  const original2 = process.env.OPERATOR_MODE;
  process.env.OPERATOR_MODE = "1";
  try {
    await metaStateSweepTool.handler({ apply: true });
  } finally {
    process.env.OPERATOR_MODE = original2;
  }

  const second = readFileSync(summaryPath, "utf8");

  // Same content except the last_generated_at timestamp
  const normalize = (s) => s.replace(/\*\*Generated:\*\* .*/, "**Generated:** <timestamp>");
  assert.strictEqual(normalize(first), normalize(second), "Summary should be idempotent (same content, different timestamp)");
});
