/**
 * Preservation baseline — gate area (issue #155, stage 1 of #154).
 *
 * Characterization of externally visible Bash-gate / write-gate / inbound-gate
 * behavior through the highest existing observable seam: the stable evaluator
 * interfaces (evaluateBashGate / evaluateInboundGate) plus the shared
 * root-defaulting helper (findProjectRoot). These tests close ONLY the
 * demonstrated coverage gaps the characterization inventory found; behavior
 * already pinned by evaluate-bash-gate.test.js / evaluate-write-gate.test.js /
 * evaluate-inbound-gate.test.js / gate-* integration tests is NOT duplicated.
 *
 * Preserved observable contract: the current program and independently
 * maintained tests remain the baseline for gate, Rule, delivery, startup, and
 * runtime behavior. These tests assert that contract directly — they are
 * characterization of the current observable behavior, NOT differential
 * old-versus-new comparisons and NOT an oracle generated by the old
 * implementation.
 *
 * Gaps closed here (each verified against the running implementation before
 * being asserted):
 *   1. Precedence: a promoted-rule escalate beats a records/** path-write
 *      hard-block and a side-effect-import hard-block (early return in
 *      evaluate-bash-gate.js).
 *   2. Precedence: constraint hard-block vs path hard-block — the constraint
 *      wins (exact fold order).
 *   3. Precedence: first-class constraint + gate-verb double-match — the
 *      constraint result survives when both are soft-blocks; the gate-verb
 *      replaces only a constraint that resolved "ok".
 *   4. Promoted-rule result carries the verbatim reason string
 *      `Promoted rule "<id>" matched: <pattern>` and the complete metadata
 *      (rule_id, meta_state_id, pattern_type, event_source, match_origin,
 *      candidate_kind).
 *   5. Staleness escalate populates observation_id + the staleness reason text.
 *   6. Root defaulting: GATE_ROOT env branch + records/-walk fallback, and the
 *      evaluators' root-less defaulting to that resolution.
 *   7. Malformed input: non-string non-null command → ok.
 *   8. Propagated failure: a malformed meta-state.jsonl does not crash the
 *      evaluator — loadPromotedRules swallows and the gate stays fail-open.
 *   9. Fail-closed boundary spellings: `>>` append to records/** and
 *      runtime-state.jsonl, `tee` to .loop/runtime-tracking.json, and the
 *      decision-log path-prefix looseness (absolute / `.//` / `.git`-style
 *      prefixes, `.gate-decision.log.backup` over-match).
 *  10. Inbound gate: stale_signature field, the suppression mechanism
 *      (same-signature-in-window → "already surfaced"; window expiry or
 *      signature change → full re-emit), and the steering pointer.
 *
 * Not gaps (already covered by the existing suite, per the #155 inventory):
 * legacy Hint identity/content/channel/order/budget/truncation (hint-registry/
 * hint-renderer/rule-derived-process-hints unit tests + loop-get-instruction
 * e2e + mcp-wire-budget/cli-sessionstart-banner), and startup fail-open
 * degradation with visible errors (e2e session-start-inject-discoverability/
 * process-hints, toolchain-failure-capture, gate-recurrence, git preflight
 * hooks). No tests were added for those areas because no demonstrated gap
 * existed.
 *
 * Stop/rollback (caller cutover): if any later migration stage routes a caller
 * through a new deep interface whose output diverges from these assertions on
 * any input in this characterization set, that stage stops at its seam and
 * restores the prior wiring (see #154 and the #155 ticket comment for the
 * full per-stage condition).
 *
 * Deletion condition (ticket #155): this file is the permanent interface
 * coverage for the preservation baseline. Temporary old-versus-new differential
 * fixtures and compatibility-adapter comparisons added by later migration
 * stages are removed after the corresponding native interface has permanent
 * behavior coverage; this file is NOT removed by that condition.
 *
 * Runtime ownership scope: characterization only — no runtime-owned adapter or
 * configuration is read or modified beyond the in-repo fixtures below.
 */

import { test } from "vitest";
import assert from "node:assert";
import { mkdtempSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import {
  evaluateBashGate,
  DECISION_LOG_WRITE_REASON,
} from "./evaluate-bash-gate.js";
import {
  evaluateInboundGate,
  buildSteeringPointer,
  SUPPRESS_WINDOW_MS,
} from "./evaluate-inbound-gate.js";
import { findProjectRoot } from "./gate-logic.js";

// ── helpers ──

function makeRoot() {
  return mkdtempSync(join(tmpdir(), "preservation-baseline-"));
}

function writeRuntimeState(root, entries) {
  const lines = entries.map((e) => JSON.stringify(e)).join("\n");
  writeFileSync(join(root, "runtime-state.jsonl"), lines + "\n");
}

// Write a promoted regex rule into the fixture root's meta-state.jsonl.
function writePromotedRule(root, { id, pattern }) {
  const rule = JSON.stringify({
    id,
    entry_kind: "rule",
    origin: "meta-test-origin",
    status: "active",
    enforcement: "gate",
    pattern_type: "regex",
    pattern,
    description: "A sufficiently long test description for schema validation to pass.",
    promoted_at: new Date().toISOString(),
    promoted_by: "test",
  });
  writeFileSync(join(root, "meta-state.jsonl"), rule + "\n");
}

// ── 1. Precedence: promoted-rule escalate beats hard-block ──

test("promoted-rule escalate beats a records/** path-write hard-block", () => {
  const root = makeRoot();
  // The promoted rule fires on the same command that hard-blocks on
  // records/**; the evaluate-bash-gate.js early return keeps the escalate.
  writePromotedRule(root, { id: "rule-precedence-path", pattern: "records/meta" });
  const result = evaluateBashGate({ command: "echo x > records/meta/test.json", root });
  assert.strictEqual(result.decision, "escalate");
  assert.strictEqual(result.rule_id, "rule-precedence-path");
  assert.strictEqual(result.hard_block, undefined, "escalate must not be a hard block");
});

test("promoted-rule escalate beats a side-effect-import hard-block", () => {
  const root = makeRoot();
  writePromotedRule(root, { id: "rule-precedence-import", pattern: "vnstock_data" });
  const result = evaluateBashGate({ command: 'python -c "import vnstock_data"', root });
  assert.strictEqual(result.decision, "escalate");
  assert.strictEqual(result.rule_id, "rule-precedence-import");
  assert.notStrictEqual(result.constraint_type, "side-effect-import", "the import hard-block must not win");
});

// ── 2. Precedence: constraint hard-block vs path hard-block ──

test("constraint hard-block beats a path-write hard-block (fold order)", () => {
  const root = makeRoot();
  const result = evaluateBashGate({
    command: 'python -c "import vnstock_data" && echo x > records/meta/test.json',
    root,
  });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.hard_block, true);
  assert.strictEqual(result.constraint_type, "side-effect-import", "constraint hard-block must win the fold");
});

// ── 3. Precedence: first-class constraint + gate-verb double-match ──

test("constraint soft-block + gate-verb soft-block → constraint result survives", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: "pip install vnstock && bash -c 'echo hi'", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.constraint_type, "package-manager", "the constraint result must survive the replace logic");
});

test("constraint ok + gate-verb soft-block → gate-verb replaces the constraint result", () => {
  const root = makeRoot();
  writeRuntimeState(root, [
    { id: "obs-vnstock", kind: "budget-state", status: "active", affected_system: "vnstock", timestamp: new Date().toISOString() },
  ]);
  const result = evaluateBashGate({ command: "pip install vnstock && bash -c 'echo hi'", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.constraint_type, "gate-verb:bash", "the stricter non-ok gate-verb must replace the ok constraint");
});

test("constraint ok + gate-verb ok → ok", () => {
  const root = makeRoot();
  writeRuntimeState(root, [
    { id: "obs-vnstock", kind: "budget-state", status: "active", affected_system: "vnstock", timestamp: new Date().toISOString() },
    { id: "obs-bash", kind: "budget-state", status: "active", affected_system: "gate-verb:bash", timestamp: new Date().toISOString() },
  ]);
  const result = evaluateBashGate({ command: "pip install vnstock && bash -c 'echo hi'", root });
  assert.strictEqual(result.decision, "ok");
});

// ── 4. Promoted-rule verbatim reason + complete metadata ──

test("promoted-rule escalate carries the verbatim reason and complete metadata", () => {
  const root = makeRoot();
  writePromotedRule(root, { id: "rule-metadata", pattern: "\\bdocker\\b" });
  const result = evaluateBashGate({ command: "docker run ubuntu", root });
  assert.strictEqual(result.decision, "escalate");
  assert.strictEqual(result.reason, 'Promoted rule "rule-metadata" matched: \\bdocker\\b');
  assert.strictEqual(result.rule_id, "rule-metadata");
  assert.strictEqual(result.meta_state_id, "rule-metadata");
  assert.strictEqual(result.pattern_type, "regex");
  assert.strictEqual(result.event_source, "bash-gate-evaluator");
  assert.strictEqual(result.match_origin, "executable");
  assert.strictEqual(result.candidate_kind, "ordinary-rule-fire");
});

// ── 5. Staleness escalate: observation_id + reason text ──

test("staleness escalate populates observation_id and the reason text", () => {
  const root = makeRoot();
  writeRuntimeState(root, [
    {
      id: "obs-stale-escalate",
      kind: "budget-state",
      status: "active",
      affected_system: "vnstock",
      timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
  ]);
  const markerPath = join(root, "marker.json");
  writeFileSync(markerPath, JSON.stringify({ timestamp: new Date().toISOString() }));
  process.env.GATE_MARKER_PATH = markerPath;
  try {
    const result = evaluateBashGate({ command: "pip install vnstock", root });
    assert.strictEqual(result.decision, "escalate");
    assert.strictEqual(result.inbound_gate, true);
    assert.strictEqual(result.observation_id, "obs-stale-escalate");
    assert.ok(result.reason.includes('Observation "obs-stale-escalate" updated at'), `reason must name the observation; got: ${result.reason}`);
    assert.ok(result.reason.includes("may be stale"), `reason must carry the staleness framing; got: ${result.reason}`);
  } finally {
    delete process.env.GATE_MARKER_PATH;
  }
});

// ── 6. Root defaulting ──

test("findProjectRoot honors GATE_ROOT, then falls back to the records/-walk root", () => {
  const prev = process.env.GATE_ROOT;
  const tempRoot = makeRoot();
  process.env.GATE_ROOT = tempRoot;
  try {
    assert.strictEqual(findProjectRoot(), tempRoot, "GATE_ROOT branch must win when set");
  } finally {
    if (prev === undefined) {
      delete process.env.GATE_ROOT;
    } else {
      process.env.GATE_ROOT = prev;
    }
  }
  // Walk-up fallback: the repo root contains records/.
  const walked = findProjectRoot();
  assert.ok(existsSync(join(walked, "records")), "walk-up fallback must resolve to a root containing records/");
});

test("evaluateBashGate without root consults GATE_ROOT's rule registry", () => {
  const root = makeRoot();
  writePromotedRule(root, { id: "rule-only-in-temp-root", pattern: "\\bno-such-cmd\\b" });
  const prev = process.env.GATE_ROOT;
  process.env.GATE_ROOT = root;
  try {
    const result = evaluateBashGate({ command: "no-such-cmd --flag" });
    assert.strictEqual(result.decision, "escalate");
    assert.strictEqual(result.rule_id, "rule-only-in-temp-root", "root-less evaluation must resolve GATE_ROOT");
  } finally {
    if (prev === undefined) {
      delete process.env.GATE_ROOT;
    } else {
      process.env.GATE_ROOT = prev;
    }
  }
});

// ── 7. Malformed input ──

test("non-string non-null command → ok (guard branch)", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: 42, root });
  assert.strictEqual(result.decision, "ok");
});

// ── 8. Propagated failure: malformed rule registry stays fail-open ──

test("malformed meta-state.jsonl does not crash the evaluator (fail-open)", () => {
  const root = makeRoot();
  writeFileSync(join(root, "meta-state.jsonl"), "{not-valid-json\n");
  const result = evaluateBashGate({ command: "ls -la", root });
  assert.strictEqual(result.decision, "ok", "a malformed registry must degrade, not throw");
});

// ── 9. Fail-closed boundary spellings ──

test(">> append to records/** → block (records-class reason)", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: "echo x >> records/meta/test.json", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.hard_block, true);
  assert.ok(result.reason.includes("records"), `expected records-class reason; got: ${result.reason}`);
});

test(">> append to runtime-state.jsonl → block (runtime-state reason)", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: "echo x >> runtime-state.jsonl", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.hard_block, true);
  assert.ok(result.reason.includes("runtime-state"), `expected runtime-state reason; got: ${result.reason}`);
});

test("tee to .loop/runtime-tracking.json → block (records-class reason)", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: "echo x | tee .loop/runtime-tracking.json", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.hard_block, true);
  assert.ok(result.reason.includes("records"), `expected records-class reason; got: ${result.reason}`);
});

test("decision-log path-prefix looseness: absolute / .// / .git-style prefixes all block with the dedicated reason", () => {
  const root = makeRoot();
  const spellings = [
    "echo x >> /repo/.claude/coordination/.gate-decision.log",
    "echo x >> .//.claude//coordination//.gate-decision.log",
    "echo x >> .git/.claude/coordination/.gate-decision.log",
  ];
  for (const command of spellings) {
    const result = evaluateBashGate({ command, root });
    assert.strictEqual(result.decision, "block", `expected block for ${command}`);
    assert.strictEqual(result.hard_block, true, `expected hard block for ${command}`);
    assert.strictEqual(result.reason, DECISION_LOG_WRITE_REASON, `dedicated reason for ${command}`);
  }
});

test("decision-log accepted over-match: .gate-decision.log.backup → block with the dedicated reason", () => {
  const root = makeRoot();
  const result = evaluateBashGate({ command: "echo x >> .claude/coordination/.gate-decision.log.backup", root });
  assert.strictEqual(result.decision, "block");
  assert.strictEqual(result.hard_block, true);
  assert.strictEqual(result.reason, DECISION_LOG_WRITE_REASON);
});

// ── 10. Inbound gate: stale_signature, suppression, steering pointer ──

function writeStaleObservation(root, { id = "obs-stale" } = {}) {
  writeRuntimeState(root, [
    {
      id,
      kind: "budget-state",
      status: "active",
      affected_system: "vnstock",
      timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    },
  ]);
}

test("inbound-gate warn decision carries stale_signature", () => {
  const root = makeRoot();
  writeStaleObservation(root);
  const result = evaluateInboundGate({ prompt: "I cleared the device", root });
  assert.strictEqual(result.decision, "warn");
  assert.ok(result.stale_signature, "stale_signature must be populated on a warn");
  assert.strictEqual(result.stale_signature, "obs-stale");
});

test("same stale signature within the suppress window → 'already surfaced' pointer", () => {
  const root = makeRoot();
  writeStaleObservation(root);
  const now = Date.now();
  const first = evaluateInboundGate({ prompt: "I cleared the device", root, now });
  const second = evaluateInboundGate({
    prompt: "I cleared the device",
    root,
    priorSignature: first.stale_signature,
    priorTs: now - 1000,
    now,
  });
  assert.strictEqual(second.decision, "warn");
  assert.ok(second.context_message.includes("already surfaced this session"), "repeat within window must collapse to the one-line pointer");
  assert.ok(!second.context_message.includes("Operator message contains a state-change signal"), "the full pointer must not re-emit");
});

test("expired suppress window re-emits the full pointer", () => {
  const root = makeRoot();
  writeStaleObservation(root);
  const now = Date.now();
  const first = evaluateInboundGate({ prompt: "I cleared the device", root, now });
  const expired = evaluateInboundGate({
    prompt: "I cleared the device",
    root,
    priorSignature: first.stale_signature,
    priorTs: now - SUPPRESS_WINDOW_MS - 1000,
    now,
  });
  assert.strictEqual(expired.decision, "warn");
  assert.ok(!expired.context_message.includes("already surfaced this session"), "an expired window must re-emit the full pointer");
  assert.ok(expired.context_message.includes("state-change signal"), "the full pointer must re-emit");
});

test("changed stale signature re-emits the full pointer", () => {
  const root = makeRoot();
  writeStaleObservation(root, { id: "obs-a" });
  const now = Date.now();
  evaluateInboundGate({ prompt: "I cleared the device", root, now });
  // Surface a second stale observation alongside the first → the signature changes.
  writeRuntimeState(root, [
    {
      id: "obs-a",
      kind: "budget-state",
      status: "active",
      affected_system: "vnstock",
      timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    },
    {
      id: "obs-b",
      kind: "budget-state",
      status: "active",
      affected_system: "vnstock",
      timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    },
  ]);
  const changed = evaluateInboundGate({
    prompt: "I cleared the device",
    root,
    priorSignature: "obs-a",
    priorTs: now - 1000,
    now,
  });
  assert.strictEqual(changed.decision, "warn");
  assert.strictEqual(changed.stale_signature, "obs-a,obs-b");
  assert.ok(!changed.context_message.includes("already surfaced this session"), "a changed stale set must re-emit");
});

test("buildSteeringPointer returns the canonical pull pointer", () => {
  assert.strictEqual(
    buildSteeringPointer(),
    "Loop steering (pull): loop_describe({tier:'warm'}) | hints: .claude/session-context.json | one: loop_get_instruction({key})",
  );
});
